---
title: "city-GIS-data"
author: "Matthew Ho"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning = F}
library(opendatatoronto)
library(dplyr)
library(stringr)
library(mapview)
library(leafem)
library(leaflet)
library(tidyr)
library(arules)
library(lmerTest)



mapviewOptions(fgb = FALSE)

	
# get package
package <- show_package("9a284a84-b9ff-484b-9e30-82f22c1780b9")
package
 
# get all resources for this package
resources <- list_package_resources("9a284a84-b9ff-484b-9e30-82f22c1780b9")
 
# identify datastore resources; by default, Toronto Open Data sets datastore resource format to CSV for non-geospatial and GeoJSON for geospatial resources
datastore_resources <- filter(resources, tolower(format) %in% c('csv', 'geojson'))
 
# load the first datastore resource as a sample
data <- filter(datastore_resources, row_number()==1) %>% get_resource()
unique(data$AREA_CLASS)

data_parks <- data %>% 
  filter(AREA_CLASS == "Park")

data_other_unknown <- data %>% 
  filter(AREA_CLASS == "OTHER_UNKNOWN")

data %>% 
  filter(AREA_NAME == "ASQUITH")

leaflet() %>% 
  addTiles() %>% 
  addPolygons(data = data_parks$geometry, 
              popup = data_parks$AREA_NAME)

```

```{r POPS_only}
POPdata <- read.csv("COT_POPS_points.csv")


POPsample <- POPdata %>% 
  filter(status == "EXISTING") %>% 
  filter(str_detect(description, "parkette") | 
           str_detect(description, "garden") |
           str_detect(description, "open space") | 
           str_detect(description, "open spaces") |
           str_detect(description, "landscaping") |
           str_detect(description, "landscaped")) %>% 
  group_by(ward_and_num) %>% 
  sample_frac(0.5)


leaflet(POPsample) %>% 
  addTiles() %>% 
  addMarkers(~longitude, 
             ~latitude, 
             popup = paste("Address:", POPsample$location, "<br>",
                           "Description:", POPsample$description, "<br>",
                           "Ward:", POPsample$ward_and_num))

```

```{r data}
site_info <- read.csv("site_info.csv")
sampled_data <- read.csv("sampled_data.csv")

# Pivoting
sampled_data_long <- sampled_data %>% 
  pivot_longer(cols = c("a444_Yonge", "a200_Bloor_E", "a76_Davenport", "a130_Adelaide_W", "a77_Adelaide_W", "a40_King_W", "a161_Bay_W", "a220_Bay", "a123_Front"),
               names_to = c("site"),
               names_repair = ~ make.unique(.x),
               values_to = c("species"))

# Calculating native percentages

native_percentages <- sampled_data_long %>% 
  filter(!is.na(species.1)) %>% 
  group_by(site) %>% 
  summarise(perc.native = (sum(native == "Y"))/n())

# Merging native percentages with site info

site_data <- left_join(site_info, native_percentages, by = c("site.address" = "site"), all.x=TRUE)

# Binning each random variable

site_data_binned <- site_data %>% 
  mutate(build.height.bin = discretize(build.height.ft,
                                       method = "interval",
                                       breaks = 3,
                                       labels = c("short", "mid", "tall"))) %>% 
  mutate(POPS.age.bin = discretize(POPS.age,
                                       method = "interval",
                                       breaks = 3,
                                       labels = c("recent", "interm", "old")))

# Making each ward a factor

as.factor(site_data_binned$ward.income)
as.factor(site_data_binned$build.type)

# LMER

m1 <- lmer(perc.native ~ site.area +
             (1 | build.height.bin) + 
             (1 | POPS.age.bin) +
             (1 | ward.income) + 
             (1 | build.type),
           data = site_data_binned)

summary(m1)

plot(m1)


# NMDS Plots
library(vegan)






```


